version: '3.2'

services:

  Api:
    build:
      dockerfile: Dockerfile.dev
    ports: 
      - 8080:80
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src/Api:/code/app
